# Generated by Django 4.2.7 on 2023-12-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyresponses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyresponses',
            options={'managed': True},
        ),
    ]
