# Generated by Django 4.2.7 on 2023-12-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firebase_uid', models.CharField(max_length=255, unique=True)),
                ('product_id', models.CharField(max_length=255)),
                ('product_title', models.CharField(db_column='Product_Title', max_length=1024)),
                ('product_per_price', models.CharField(db_column='Product_Per_Price', max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'basket2',
                'managed': False,
            },
        ),
    ]
