# Generated by Django 4.2.7 on 2023-12-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezpill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='basket',
            fields=[
                ('basket_id', models.AutoField(primary_key=True, serialize=False)),
                ('pill_1', models.CharField(blank=True, max_length=45, null=True)),
                ('pill_2', models.CharField(blank=True, max_length=45, null=True)),
                ('pill_3', models.CharField(blank=True, max_length=45, null=True)),
                ('pill_4', models.CharField(blank=True, max_length=45, null=True)),
                ('pill_5', models.CharField(blank=True, max_length=45, null=True)),
                ('pill_6', models.CharField(blank=True, max_length=45, null=True)),
                ('pill_7', models.CharField(blank=True, max_length=45, null=True)),
                ('pill_8', models.CharField(blank=True, max_length=45, null=True)),
                ('pill_9', models.CharField(blank=True, max_length=45, null=True)),
                ('pill_10', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'basket',
                'managed': False,
            },
        ),
    ]
