# Generated by Django 4.2.7 on 2023-12-08 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezpill', '0002_basket'),
        ('ezpill', '0003_basket2_surveyresponses'),
    ]

    operations = [
    ]
