# Generated by Django 4.2.7 on 2023-12-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezpill', '0004_merge_0002_basket_0003_basket2_surveyresponses'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='surveyresponses',
            table='SurveyResponses',
        ),
    ]
