# Generated by Django 4.2.7 on 2023-12-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.TextField(blank=True, db_column='Image_URL', null=True)),
                ('product_title', models.TextField(blank=True, db_column='Product_Title', null=True)),
                ('product_manufacture', models.TextField(blank=True, db_column='Product_Manufacture', null=True)),
                ('product_price', models.TextField(blank=True, db_column='Product_Price', null=True)),
                ('product_per_price', models.TextField(blank=True, db_column='Product_Per_Price', null=True)),
                ('product_usage', models.TextField(blank=True, db_column='Product_Usage', null=True)),
                ('product_precautions', models.TextField(blank=True, db_column='Product_Precautions', null=True)),
                ('product_ingredient_information', models.TextField(blank=True, db_column='Product_Ingredient_Information', null=True)),
                ('review', models.TextField(blank=True, db_column='Review', null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
